### ISSUE TITLE
Odyssey is being indexed as hansel in Google

### ISSUE THREAD

**Issue by sebastiantoh** [0dy553y/odyssey#132]
![image](https://user-images.githubusercontent.com/24363622/139517451-18af95db-2912-45c5-a6ee-26588ffbf8f9.png)
- https://www.google.com/search?q=site%3Aodyssey-app.com

Clicking on the link by Google also gives the following warning:

![image](https://user-images.githubusercontent.com/24363622/139517484-f6e74017-7112-426b-8ad5-38d4d2e1da4f.png)

**Comment by ianyong** [comment]
Looking into this but might take a while for DNS TXT records to propagate so that Google can verify that the domain is under my control.

**Comment by ianyong** [comment]
Not sure why Google is indexing `https://www.odyssey-app.com` instead of `https://odyssey-app.com` when Hansel has `https://hansel-app.com` indexed. I've added a certificate for `www.odyssey-app.com` and requested for Google to re-index the site which might take a while.

**Comment by ianyong** [comment]
Thanks Google

![image](https://user-images.githubusercontent.com/5585517/139567571-f8aab9db-91ca-4f54-b7d1-2d6b558a8e5c.png)

Going to reopen this issue while I try some stuff to see if I can clear that erroneous search result.

**Comment by ianyong** [comment]
Search results have updated!

![chrome_5cpC7W18bE](https://user-images.githubusercontent.com/5585517/140005021-a3370a75-7d2b-40c8-af88-6694f66abdf3.png)
