### ISSUE TITLE
Map bug

### ISSUE THREAD

**Issue by jialin7878** [0dy553y/odyssey#259]
<img width="1509" alt="Screenshot 2021-11-06 at 10 49 10 PM" src="https://user-images.githubusercontent.com/59867654/140613790-518b5eea-4fba-41e9-88db-a44e6ae804da.png">

**Comment by jialin7878** [comment]
<img width="788" alt="Screenshot 2021-11-06 at 10 56 57 PM" src="https://user-images.githubusercontent.com/59867654/140614000-791448bd-20f2-4930-84ba-d525e6b888f5.png">
hmm I can't seem to replicate it on localhost, not sure why this will be undefined too -- anybody has an idea?

**Comment by sebastiantoh** [comment]
`currentTaskNum` in the `if` statement should be `f.currentTaskNum` instead?

**Comment by jialin7878** [comment]
omgg HAHA thank u!
