### ISSUE TITLE
Style login/register on desktop view?

### ISSUE THREAD

**Issue by jialin7878** [0dy553y/odyssey#265]
<img width="1509" alt="Screenshot 2021-11-07 at 1 08 07 AM" src="https://user-images.githubusercontent.com/59867654/140617898-ff89d03c-3bc4-47b5-a5c6-1e0c3b3d8b7d.png">
wrong screenshot haha

**Comment by ming-00** [comment]
Imma do it with #200 ;') help

**Comment by jialin7878** [comment]
oh didn't see, thanks!
