### ISSUE TITLE
Challenge Completed Modal is not displaying correct prize?

### ISSUE THREAD

**Issue by sebastiantoh** [0dy553y/odyssey#288]
![image](https://user-images.githubusercontent.com/24363622/140649391-d9fb85ee-d96a-4e24-92a6-e974c23b017f.png)

Displays a generic trophy instead of the expected journal
- Might be because my DB state is messed up, but the map does correctly show the journal

Also, maybe if the challenge is completed, the map shouldn't auto close?

**Comment by jialin7878** [comment]
> ![image](https://user-images.githubusercontent.com/24363622/140649391-d9fb85ee-d96a-4e24-92a6-e974c23b017f.png)
> 
> Displays a generic trophy instead of the expected journal
> 
> * Might be because my DB state is messed up, but the map does correctly show the journal

is this on localhost?

> Also, maybe if the challenge is completed, the map shouldn't auto close?

i think i did this here https://github.com/0dy553y/odyssey/pull/247/commits/09312cc214e98fe35bfb58f5c974d598a7d3e63c
and it worked hmm...will see if i can replicate tq

**Comment by sebastiantoh** [comment]
> is this on localhost?

yep!

> i think i did this here [09312cc](https://github.com/0dy553y/odyssey/commit/09312cc214e98fe35bfb58f5c974d598a7d3e63c) and it worked hmm...will see if i can replicate tq

oops, this is my bad. my db state is messed up

**Comment by sebastiantoh** [comment]
![image](https://user-images.githubusercontent.com/24363622/140666690-1531db71-1fc3-4b29-ad3c-bc7ea0885353.png)
![image](https://user-images.githubusercontent.com/24363622/140666707-8d88d5ca-8113-4cdc-a534-99fc69fd808f.png)

I think the issue is because we pass in a prizePath instead of a prizeName to get `getPrize` function

**Comment by jialin7878** [comment]
ah, nice catch thanks! will fix
