### ISSUE TITLE
horizontal scroll on user task card

### ISSUE THREAD

**Issue by jialin7878** [0dy553y/odyssey#299]
![Screenshot 2021-11-09 at 1 16 09 AM](https://user-images.githubusercontent.com/59867654/140787823-4dfced62-76a5-4a3e-8767-b45595b4b22d.png)

sorry not too sure if this has been filed before, feel free close if it has

**Comment by ianyong** [comment]
Hmm, I can't seem to replicate this, even with long URLs; they just wrap around.

**Comment by jialin7878** [comment]
ah I see! I also realise my db is outdated, i think we can close this
