### ISSUE TITLE
Should show loading instead of no posts yet(?)

### ISSUE THREAD

**Issue by jialin7878** [0dy553y/odyssey#310]

**Comment by ming-00** [comment]
Actually, I'm not very sure what the best way to implement this is 😅 Is there a way you would recommend?

**Comment by sebastiantoh** [comment]
hmm, yea. I think it's kinda hard because we forced all our operations to be synchronous. I think a hacky way would be to have a local `isLoading` state, and then we pass a `() => setIsLoading(false)` callback to the `loadAllPosts` function, which it will call after the fetch is complete?

**Comment by ming-00** [comment]
Ooh thanks! Sounds good 😙
